---
  ########################
  #### Python status #####
  ########################
  - name: Check Python version | if version lower than 3.5 do nothing and let me know it.
    command: python3 --version
    register: python_version_result
    failed_when: python_version_result.stdout | regex_replace('Python ', '') is version(PYTHON_VERSION, '<')

  - name: Compare Python versions
    debug:
      msg: "{{ python_version_result.stdout }} < {{ PYTHON_VERSION }} | false | Everything is OK"

  - name: Install python3-requests
    apt:
      name: python3-requests
      state: present
      update_cache: yes
    when: ansible_hostname == 'pardus'
