---
  - name: Check if Python is already latest
    command: python3 --version
    register: python_version_result
    failed_when: python_version_result.stdout | regex_replace('Python ', '') is version(python_version, '<')

  - name: Print Python version
    debug:
      msg: "Python Version(variable): {{ python_version }} | Python version(active): {{ python_version_result.stdout }}"