---
  - name: Check Python version | if version lower than 3.5 do nothing and let me know it.
    command: python3 --version
    register: python_version_result
    failed_when: python_version_result.stdout | regex_replace('Python ', '') is version(python_version, '<')

  - name: Compare Python versions
    debug:
      msg: "{{ python_version_result.stdout }} < {{ python_version }} | activePythonVersion < myPythonVersionVariable"

  - name: Install python3-apt using raw module
    raw: |
        apt-get update && apt-get install -y python3-apt
        changed_when: false

  - name: installing packages for python env
    become: yes
    apt:
      name:
        - python3-pip
      update_cache: yes