---
  - name: Check Python is specific version I need
    command: python3 --version
    register: python_version_result
    failed_when: python_version_result.stdout | regex_replace('Python ', '') is version(python_version, '<')

  - name: Check Python versions
    debug:
      msg: "{{ python_version_result.stdout }} < {{ python_version }} | activePythonVersion < myPythonVersion"