---
  ########################
  ### Check container ####
  ########################
- name: Check Docker version
  command: docker --version
  register: dockerVersion

- name: Print Docker version
  debug:
    msg: "Docker Version: {{ dockerVersion.stdout }}"

- name: Get info for Docker container
  docker_container_info:
    name: "{{ CONTAINER_NAME }}-{{ APP_PROJECT_NAME }}"
  register: isContainer

- name: Does container exist?
  debug:
    msg: "The container {{ 'exists' if isContainer.exists else 'does not exist' }}"

  ########################
  ### Container exist ####
  ########################
- name: Stop the container if it exists
  docker_container:
    name: "{{ CONTAINER_NAME }}-{{ APP_PROJECT_NAME }}"
    state: stopped
  when: isContainer.exists

- name: Remove the container if it exists
  docker_container:
    name: "{{ CONTAINER_NAME }}-{{ APP_PROJECT_NAME }}"
    state: absent
  when: isContainer.exists

- name: Remove the container image after the container is stopped
  docker_image:
    name: "{{ IMAGE_NAME }}"
    state: absent
  when: isContainer.exists

- name: Pull and run the container if it exists
  docker_container:
    name: "{{ CONTAINER_NAME }}-{{ APP_PROJECT_NAME }}"
    image: "{{ IMAGE_NAME }}"
    ports:
      - "{{ APP_EXTERNAL_PORT }}:{{ APP_INTERNAL_PORT }}"
    state: started
    env:
      APP_PROJECT_NAME: "{{ APP_PROJECT_NAME }}"
      APP_INTERNAL_PORT: "{{ APP_INTERNAL_PORT }}"
      APP_EXTERNAL_PORT: "{{ APP_EXTERNAL_PORT }}"
      CONNECT_DB: "{{ CONNECT_DB }}"
      CONNECT_REDIS: "{{ CONNECT_REDIS }}"
    restart_policy: always
    command: ["npm", "run", "start"]
  when: isContainer.exists

- name: Print the status of the container
  debug:
    msg: "The container status is {{ isContainer.container['State']['Status'] }}"
  when: isContainer.exists

  ########################
  # Container not exist ##
  ########################
- name: Pull and run the container if it is not exists
  docker_container:
    name: "{{ CONTAINER_NAME }}-{{ APP_PROJECT_NAME }}"
    image: "{{ IMAGE_NAME }}"
    ports:
      - "{{ APP_EXTERNAL_PORT }}:{{ APP_INTERNAL_PORT }}"
    state: started
    env:
      APP_PROJECT_NAME: "{{ APP_PROJECT_NAME }}"
      APP_INTERNAL_PORT: "{{ APP_INTERNAL_PORT }}"
      APP_EXTERNAL_PORT: "{{ APP_EXTERNAL_PORT }}"
      CONNECT_DB: "{{ CONNECT_DB }}"
      CONNECT_REDIS: "{{ CONNECT_REDIS }}"
    restart_policy: always
    command: ["npm", "run", "start"]
  when: not isContainer.exists
