---
- name: Check Docker version
  command: docker --version
  register: dockerVersion

- name: Print version
  debug:
    msg: "Docker Version: {{ dockerVersion.stdout }}"

- name: Get info for container
  docker_container_info:
    name: "{{ CONTAINER_NAME }}"
  register: result

- name: Does container exist?
  debug:
    msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

- name: Stop the container if it exists
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    state: stopped
  when: result.exists

- name: Print the status of the container
  debug:
    msg: "The container status is {{ result.container['State']['Status'] }}"
  when: result.exists