---
- name: Creates a directory
  file:
    path: "/tmp/{{ DIRECTORY_NAME }}"
    state: directory

- name: Write a echo message
  command:
  cmd: echo
  argv:
    - "Jenkins message => {{ MESSAGE }}"