---
- name: Creates a directory
  file:
    path: "/tmp/{{ DIRECTORY_NAME }}{{ MESSAGE }}"
    state: directory

- name: Execute shell commands on targets
  shell: echo "Message from Jenkins: {{ MESSAGE }}"
  register: echo_output

- name: Show message command
  debug:
    var: echo_output.stdout