---
- name: Check if Python is already latest
  command: python3 --version
  register: python_version_result
  failed_when: "{{ python_version_result.stdout | replace('Python ', '') | version_compare(python_version, '>=') }}"

- name: Print Python version
  debug:
    msg: "Python Version: {{ python_version_result.stdout }}"

- name: Check Docker version
  command: docker --version
  register: dockerVersion

- name: Print Docker version
  debug:
    msg: "Docker Version: {{ dockerVersion.stdout }}"

- name: Get info for container
  docker_container_info:
    name: "{{ CONTAINER_NAME }}"
  register: result

- name: Does container exist?
  debug:
    msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

- name: Print the status of the container
  debug:
    msg: "The container status is {{ result.container['State']['Status'] }}"
  when: result.exists