---
- name: Creates a directory
  file:
    path: "/tmp/{{ DIRECTORY_NAME }}"
    state: directory

- name: Write a message
  shell: echo "{{ MESSAGE }}"
  register: echo_output

- name: Show the message
  debug:
    var: echo_output.stdout