---
- name: Creates a directory
  file:
    path: "/tmp/{{ DIRECTORY_NAME }}"
    state: directory

- name: Check Ansible version
  command: ansible --version
  register: ansibleVersion

- name: Print version
  debug:
    msg: "Ansible Version: {{ ansibleVersion.stdout }}"