---
- name: Creates a directory
  file:
    path: "/tmp/{{ DIRECTORY_NAME }}"
    state: directory

- name: Check Docker version
  command: docker --version
  register: dockerVersion

- name: Print version
  debug:
    msg: "Docker Version: {{ dockerVersion.stdout }}"

- name: Write a message
  debug:
    msg: "Message from Jenkins: {{ MSG }}"